spring:
  application:
    name: DesafioAutonomyBase
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/autonomy-base}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    mongodb:
      uri: ${SPRING_DATA_URI:mongodb://mongo:mongo@localhost:27018/autonomy-base}
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /autonomy_base